<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Archivio.Application/Archivio.Application.csproj" />
    <ProjectReference Include="../Archivio.Domain/Archivio.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>
</Project>